import Navbar from './components/Navbar'
import { Poppins } from 'next/font/google'
import './globals.css';

const poppins = Poppins({
  subsets: ["latin"], weight: [
    "100", "200", "300", "400", "500", "600", "700", "800", "900"
  ]
});

export const metadata = {
  title: 'Eazzy Movies',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
